config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :recipe_foods, only: [:index,:new,:create, :edit, :destroy]
  resources :recipes, only: [:index,:new,:create,:show,:destroy]
  resources :foods 
  resources :users
  patch 'recipes/:id/toggle_public', to: 'recipes#toggle_public', as: 'toggle_public'
  get 'public_recipes', to: 'public_recipes#index'
  get 'general_shopping_list', to: 'general_shopping_list#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods

  validates :name, presence: true

  def total_price
    total = 0
    foods.each do |food|
      total += food.price * food.quantity
    end
    total
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit; end

  # POST /recipes or /recipes.json
  def create
    # @food = Food.new(food_params)
    @recipe = current_user.recipes.build(recipe_params)

    if @recipe.save
      # Post successfully created
      flash[:notice] = 'Recipe created successfully.'
      redirect_to recipes_path
    else
      # Handle validation errors
      flash[:notice] = 'Recipe not created successfully.'
      render :new
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to @recipe, notice: 'Recipe updated successfully.'
    else
      render :edit
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path, notice: 'Recipe was successfully deleted.'
  end

  def toggle_public
    @recipe = Recipe.find(params[:id])
    @recipe.update(public: !@recipe.public)
    redirect_to @recipe, notice: 'Recipe was successfully updated.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= stylesheet_link_tag 'foods', media: 'all' %>

 <%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="fields">
  <div class="field"> 
  <%= form.label :name %>
  <%= form.text_field :name %>
  </div>

  <div class="field"> 
  <%= form.label :preparation_time %>
  <%= form.text_field :preparation_time %>
  </div>

  <div class="field"> 
  <%= form.label :description %>
  <%= form.text_field :description %>
  </div>

  <div class="field"> 
  <%= form.label :cooking_time %>
  <%= form.text_field :cooking_time %>
  </div>

  <div class="field"> 
  <%= form.label :public %>
  <%= form.check_box :public, default: true %>
  </div>
  
  <div>
    <%= form.submit "Create recipe", class: "add-btn btn-hover"%>
  </div>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div class="recipe-list" id="<%= dom_id recipe %>">
 <div class="title">
 <a href = "<%= recipe_path(id: recipe.id) %>"><h4><%= recipe.name %></h4></a>
 <% if can? :delete, recipe %>
    <%= button_to 'Delete', recipe_path(recipe), method: :delete, data: { confirm: 'Are you sure you want to delete this comment?' } %>
  <% end %>
 </div>
 <p><%= recipe.description %></p>
 </div>
 
 

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>
<%= stylesheet_link_tag 'recipes', media: 'all' %>
<div class="d-flex flex-column gap-4 align-items-center">
 <div class="new-recipe">
 <%= link_to "New recipe", new_recipe_path, class: "btn btn-success" %>
 </div>
  <% @recipes.each do |recipe| %>
    <%= render recipe %>
  <% end %>
</div>  
<% if @recipes.empty? %>
  <div class="d-flex justify-content-center m-5 p-5">
    <p class="h2 text-secondary">You have no Recipes</p>
  </div>
<% end %>

app/views/recipes/new.html.erb
<div class="new-form-container">
<div class="form-container">
<div class="back">
  <h3>Add a new Recipe</h3>
  <%= link_to "Back", recipes_path %>
</div>
<%= render "form", recipe: @recipe %>
</div>
</div>

app/views/recipes/show.html.erb
<%= stylesheet_link_tag 'recipes', media: 'all' %>
<%= stylesheet_link_tag 'foods', media: 'all' %>

<p style="color: green"><%= notice %></p>
<h1 class="text-center"><%= @recipe.name %></h2>
<div class="d-flex justify-content-between px-5 py-3">
  <div>
    <p>Preparation time: <%= @recipe.preparation_time %> hour(s)</p>
    <p>Cooking time: <%= @recipe.cooking_time %> minute(s)</p>
    <p>Description: <%= @recipe.description %></p>
  </div>
<%= form_for @recipe, url: { action: :toggle_public }, method: :patch do |f| %>
  <%= f.label :public, "Public" %>
  <%= f.check_box :public, {}, true, false %>
  <%= f.submit "Save", class: "save" %>
<% end %>
</div>

<div class="d-flex justify-content-between p-3 pt-5">
<% if can? :create, @recipe %>
  <%= button_to "Generate shopping list", general_shopping_list_path, params: { recipe_id: @recipe.id }, method: :get, class: "btn btn-primary" %>
  <%= link_to 'Add Ingredient', new_recipe_food_path, class: "btn btn-primary" %>
<% end %>
</div>
<hr/>

  <div class="food-container">
    <div class="food-header">
      <h2>Ingredients</h2>
    </div>
    <table class="w-100">
      <thead>
        <tr>
          <th>Food</th>
          <th>Quantity</th>
          <th>Value</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @recipe.recipe_foods.each do |recipe_food| %>
          <%= render recipe_food %>
        <% end %>
      </tbody>
  </div>
</div>