config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :recipe_foods, only: [:index,:new,:create, :edit, :destroy]
  resources :recipes, only: [:index,:new,:create,:show,:destroy]
  resources :foods 
  resources :users
  patch 'recipes/:id/toggle_public', to: 'recipes#toggle_public', as: 'toggle_public'
  get 'public_recipes', to: 'public_recipes#index'
  get 'general_shopping_list', to: 'general_shopping_list#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update destroy]

  # GET /foods or /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    # @food = Food.new(food_params)
    @food = current_user.foods.build(food_params)

    if @food.save
      # Post successfully created
      flash[:notice] = 'Food created successfully.'
      redirect_to foods_path
    else
      # Handle validation errors
      flash[:notice] = 'Food not created successfully.'
      render :new
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food.html.erb
<%= stylesheet_link_tag 'foods', media: 'all' %>

<div id="<%= dom_id food %>">
<tr>
  <td><%= food.name %></td>
  <td><%= food.measurement_unit %></td>
  <td><%= food.price %></td>
  <td><%= food.quantity %></td>
  <td>
    <%= link_to 'Edit', edit_food_path(food) %>
    <% if can? :delete, food %>
      <%= button_to 'Delete', food_path(food), method: :delete, data: { confirm: 'Are you sure you want to delete this food?' } %>
    <% end %>
  </td>
</tr>
</div>

app/views/foods/_form.html.erb
<%= stylesheet_link_tag 'foods', media: 'all' %>

<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="fields">
  <div class="field"> 
  <%= form.label :name %>
  <%= form.text_field :name %>
  </div>

  <div class="field"> 
  <%= form.label :measurement_unit %>
  <%= form.text_field :measurement_unit %>
  </div>

  <div class="field"> 
  <%= form.label :price %>
  <%= form.text_field :price %>
  </div>

  <div class="field"> 
  <%= form.label :quantity %>
  <%= form.text_field :quantity %>
  </div>

  <div>
    <%= form.submit "Create Food", class: "add-btn btn-hover"%>
  </div>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/index.html.erb
<p style="color: green"><%= notice %></p>
<%= stylesheet_link_tag 'foods', media: 'all' %>

<div class="food-container">

<div class="new-food-container">
<%= link_to "New food", new_food_path, class: "link-btn btn-hover"%>
</div>

<% if @foods.empty? %>
<p>No food</p>
<% else %>
<table class="table-container">
  <thead>
    <tr>
      <th>Food</th>
      <th>Measurement Unit</th>
      <th>Unit Price</th>
      <th>Quantity</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @foods.each do |food| %>
      <%= render food %>
    <% end %>
  </tbody>
</table>
<% end %>
</div>

app/views/foods/new.html.erb
<div class="new-form-container">
<div class="form-container">
<div class="back">
  <h3>Add a new food</h3>
  <%= link_to "Back", foods_path %>
</div>
<%= render "form", food: @food %>
</div>
</div>

app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @food %>

<div>
  <%= link_to "Edit this food", edit_food_path(@food) %> |
  <%= link_to "Back to foods", foods_path %>

  <%= button_to "Destroy this food", @food, method: :delete %>
</div>